import type { Metadata } from "next";
import PublicShell from "@/components/PublicShell";

export const metadata: Metadata = {
  title: "Privacy Policy — Givny",
  description: "How Givny collects, uses, and protects your personal information.",
};

export default function PrivacyPolicy() {
  return (
    <PublicShell>
      <div className="max-w-4xl mx-auto px-6 py-16">
        {/* Header Section */}
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-light text-ink mb-4">
            Privacy Policy
          </h1>
          <p className="text-lg text-gray-500 max-w-2xl mx-auto leading-relaxed">
            What we collect, why we collect it, and how you stay in control of it
          </p>
        </div>

        {/* Content */}
        <div className="prose prose-lg prose-gray max-w-none">
          <div className="bg-sand rounded-3xl p-8 mb-12">
            <p className="text-gray-700 leading-relaxed text-justify mb-0">
              This Privacy Policy explains how Givny, operated by Givnt Ltd, collects, uses, shares,
              and protects your personal information when you use our website, mobile application,
              and services (the &ldquo;Platform&rdquo;). By using Givny, you agree to the collection
              and use of information as described here.
            </p>
          </div>

          <div className="space-y-12">
            <section>
              <h2 className="text-2xl font-medium text-ink mb-4">Information We Collect</h2>
              <p className="text-gray-700 leading-relaxed text-justify mb-3">
                We collect the information you give us directly, information generated by using the
                Platform, and information from your device:
              </p>
              <ul className="text-gray-700 space-y-2 ml-4">
                <li>• <strong>Account information</strong> — your name, email address, phone number, address, city, country, and profile picture.</li>
                <li>• <strong>Location</strong> — a general area (not your exact address) used to show nearby listings and estimate distance.</li>
                <li>• <strong>Listings and messages</strong> — photos, descriptions, and conditions of items you list, and the messages you exchange with other members to arrange a pickup.</li>
                <li>• <strong>Verification data</strong> — if you choose to verify your identity, the document you submit for that purpose.</li>
                <li>• <strong>Usage and device data</strong> — pages you visit, actions you take, your device type and browser, and IP address, collected automatically as you use the Platform.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-medium text-ink mb-4">How We Use Your Information</h2>
              <p className="text-gray-700 leading-relaxed text-justify mb-3">
                We use the information we collect to:
              </p>
              <ul className="text-gray-700 space-y-2 ml-4">
                <li>• Operate the Platform — matching donors with people who&apos;ve asked for an item, and showing listings near you.</li>
                <li>• Let you communicate with other members about a listing.</li>
                <li>• Confirm your identity where you&apos;ve asked to be verified, and keep the Platform safe from fraud and abuse.</li>
                <li>• Send you notifications about requests, messages, and account activity, and — where you&apos;ve opted in — push notifications and email updates.</li>
                <li>• Understand how Givny is used so we can improve it, including aggregate, non-identifying statistics like leaderboards and impact figures.</li>
                <li>• Meet our legal obligations and enforce our Terms of Service.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-medium text-ink mb-4">How We Share Your Information</h2>
              <p className="text-gray-700 leading-relaxed text-justify mb-3">
                We don&apos;t sell your personal information. We share it only in these situations:
              </p>
              <ul className="text-gray-700 space-y-2 ml-4">
                <li>• <strong>With other members</strong> — your name, profile picture, general location, and listings are visible to people browsing the Platform; your exact address is never shown; it stays between you and whoever you arrange a pickup with.</li>
                <li>• <strong>With organisations</strong> — if you list an item on behalf of an organisation, that listing is attributed to the organisation rather than to you personally.</li>
                <li>• <strong>With service providers</strong> — we use Google Firebase to host our infrastructure, store data, and send notifications; these providers only process data on our instructions.</li>
                <li>• <strong>For legal reasons</strong> — where required by law, or to protect the rights, safety, or property of Givny, our members, or the public.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-medium text-ink mb-4">Data Storage &amp; Security</h2>
              <p className="text-gray-700 leading-relaxed text-justify">
                Your information is stored on Google Firebase&apos;s cloud infrastructure, encrypted in
                transit, and protected by access controls that limit who at Givny can see it. No
                method of storage or transmission is completely secure, so while we work to protect
                your information, we can&apos;t guarantee its absolute security.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-medium text-ink mb-4">Your Rights &amp; Choices</h2>
              <p className="text-gray-700 leading-relaxed text-justify mb-3">
                You&apos;re in control of what you share:
              </p>
              <ul className="text-gray-700 space-y-2 ml-4">
                <li>• Update or correct your account details, and add or remove your profile picture, any time from Edit Profile.</li>
                <li>• Choose how precise a location you share — a nearby landmark works fine until you&apos;re ready to meet someone.</li>
                <li>• Turn push notifications on or off from your device or account settings.</li>
                <li>• Temporarily disable your account, hiding your profile and listings, from Settings.</li>
                <li>• Request a copy of your data, or ask us to delete your account and associated personal information, by contacting us below — we&apos;ll action this unless we&apos;re required to retain something by law.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-medium text-ink mb-4">Data Retention</h2>
              <p className="text-gray-700 leading-relaxed text-justify">
                We keep your information for as long as your account is active, or as needed to
                provide the Platform to you. If you delete your account, we remove or anonymise your
                personal information within a reasonable time, except where we&apos;re required to
                keep it — for example, to resolve disputes or meet a legal obligation.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-medium text-ink mb-4">Cookies &amp; Similar Technologies</h2>
              <p className="text-gray-700 leading-relaxed text-justify">
                We use cookies and similar technologies to keep you signed in, remember your
                preferences, and understand how the Platform is used. You can control cookies through
                your browser settings, though some parts of Givny may not work properly without them.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-medium text-ink mb-4">Children&apos;s Privacy</h2>
              <p className="text-gray-700 leading-relaxed text-justify">
                Givny is intended for people aged 18 and over, in line with our Terms of Service. We
                don&apos;t knowingly collect personal information from anyone under 18. If you believe
                a child has provided us with personal information, please contact us and we&apos;ll
                remove it.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-medium text-ink mb-4">Changes to This Policy</h2>
              <p className="text-gray-700 leading-relaxed text-justify">
                We may update this Privacy Policy from time to time. If we make material changes,
                we&apos;ll let you know — for example, by notice on the Platform — before they take
                effect. The date this policy was last updated is shown below.
              </p>
            </section>
          </div>

          <div className="border-t border-gray-200 pt-12 mt-16">
            <div className="text-center">
              <p className="text-gray-500 mb-2">
                For questions about this policy, or to exercise any of your rights above, contact us at{" "}
                <a href="mailto:support@givny.com" className="text-blue-600 hover:text-blue-800 underline">
                  support@givny.com
                </a>
              </p>
              <p className="text-sm text-gray-400 mb-8">
                Last updated: September 2026
              </p>

              <p className="text-sm text-gray-500 italic">
                By using Givny, you acknowledge that you have read and understood this Privacy Policy.
              </p>
            </div>
          </div>
        </div>
      </div>
    </PublicShell>
  );
}
