/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BqnCcLRbH6s
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

export function AddDonation() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-12">
      <div className="grid gap-8">
        <div>
          <h1 className="text-3xl font-bold">Add a Donation Item</h1>
          <p className="text-muted-foreground">Fill out the form below to add a new donation item.</p>
        </div>
        <div className="grid gap-6">
          <div className="grid md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="name">Item Name</Label>
              <Input id="name" placeholder="Enter item name" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="category">Item Category</Label>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Select category" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="clothing">Clothing</SelectItem>
                  <SelectItem value="electronics">Electronics</SelectItem>
                  <SelectItem value="furniture">Furniture</SelectItem>
                  <SelectItem value="books">Books</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="media">Images/Video</Label>
            <div className="flex items-center justify-center w-full">
              <label
                htmlFor="media"
                className="flex flex-col items-center justify-center w-full h-64 border-2 border-dashed rounded-lg border-muted cursor-pointer bg-muted/5 hover:bg-muted/10 transition-colors"
              >
                <div className="flex flex-col items-center justify-center pt-5 pb-6">
                  <UploadIcon className="w-10 h-10 text-muted-foreground" />
                  <p className="mb-2 text-sm text-muted-foreground">
                    <span className="font-semibold">Click to upload</span> or drag and drop
                  </p>
                  <p className="text-xs text-muted-foreground">SVG, PNG, JPG or GIF (max. 800x400px)</p>
                </div>
                <input id="media" type="file" multiple className="hidden" />
              </label>
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="info">Additional Information</Label>
            <Textarea id="info" placeholder="Enter additional details" />
          </div>
          <Button type="submit" className="w-full md:w-auto">
            Save Donation Item
          </Button>
        </div>
        <div>
          <h2 className="text-2xl font-bold">Preview</h2>
          <div className="grid gap-4 mt-4">
            <Card>
              <CardHeader>
                <CardTitle>Donation Item Preview</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="grid md:grid-cols-2 gap-4">
                    <div>
                      <p className="font-medium">Item Name:</p>
                      <p>Gently Used Sweater</p>
                    </div>
                    <div>
                      <p className="font-medium">Item Category:</p>
                      <p>Clothing</p>
                    </div>
                  </div>
                  <div>
                    <p className="font-medium">Images/Video:</p>
                    <div className="grid grid-cols-3 gap-4">
                      <img src="/placeholder.svg" width={200} height={200} alt="Donation Item" className="rounded-md" />
                      <img src="/placeholder.svg" width={200} height={200} alt="Donation Item" className="rounded-md" />
                      <img src="/placeholder.svg" width={200} height={200} alt="Donation Item" className="rounded-md" />
                    </div>
                  </div>
                  <div>
                    <p className="font-medium">Additional Information:</p>
                    <p>
                      {`This sweater is in excellent condition and was gently worn. It's a great addition to any wardrobe.`}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}

function UploadIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}
