/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bLS3fucGWjN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Separator } from "@/components/ui/separator"
import { Button } from "@/components/ui/button"

export function DonationDetails() {
  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="bg-background rounded-lg shadow-lg overflow-hidden">
          <div className="aspect-video bg-muted">
            <img
              src="/placeholder.svg"
              alt="Donation Item"
              width={800}
              height={450}
              className="object-cover w-full h-full"
            />
          </div>
          <div className="p-6">
            <div className="flex items-center gap-4">
              <Avatar className="border-2 border-background">
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div>
                <h3 className="text-lg font-semibold">John Doe</h3>
                <p className="text-sm text-muted-foreground">Donated on May 15, 2023</p>
              </div>
            </div>
            <Separator className="my-6" />
            <div className="grid gap-4">
              <p className="text-sm leading-relaxed text-muted-foreground">
                {`This donation item is a high-quality camera that I no longer need. It's in excellent condition and
                perfect for anyone looking to get into photography or upgrade their existing equipment.`}
              </p>
              <div className="grid grid-cols-2 gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Donation Item"
                  width={300}
                  height={300}
                  className="aspect-square object-cover rounded-lg"
                />
                <img
                  src="/placeholder.svg"
                  alt="Donation Item"
                  width={300}
                  height={300}
                  className="aspect-square object-cover rounded-lg"
                />
              </div>
            </div>
          </div>
        </div>
        <div className="bg-background rounded-lg shadow-lg p-6 flex flex-col gap-6">
          <div className="grid gap-2">
            <h2 className="text-2xl font-bold">Camera Donation</h2>
            <p className="text-muted-foreground">High-quality camera in excellent condition</p>
          </div>
          <div className="grid gap-4">
            <div className="grid gap-1">
              <p className="text-sm font-medium text-muted-foreground">Donor</p>
              <div className="flex items-center gap-2">
                <Avatar className="border-2 border-background">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <p className="text-sm font-medium">John Doe</p>
              </div>
            </div>
            <div className="grid gap-1">
              <p className="text-sm font-medium text-muted-foreground">Donated on</p>
              <p className="text-sm font-medium">May 15, 2023</p>
            </div>
          </div>
          <Button size="lg" className="mt-auto">
            Request Item
          </Button>
        </div>
      </div>
    </div>
  )
}
