/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/nFY3A2Qgqg6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Donation() {
  return (
    <div className="container mx-auto px-4 py-8 md:px-6 lg:px-8">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <div className="mb-6">
            <h1 className="text-2xl font-bold">Donation Details</h1>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h2 className="text-lg font-medium mb-2">Item Name</h2>
              <p>Warm Winter Coat</p>
            </div>
            <div>
              <h2 className="text-lg font-medium mb-2">Item Category</h2>
              <p>Clothing</p>
            </div>
          </div>
          <div className="mt-6">
            <h2 className="text-lg font-medium mb-2">Images/Videos</h2>
            <div className="grid grid-cols-2 gap-4">
              <img src="/placeholder.svg" width="300" height="200" alt="Donation Item" className="rounded-md" />
              <img src="/placeholder.svg" width="300" height="200" alt="Donation Item" className="rounded-md" />
            </div>
          </div>
          <div className="mt-6">
            <h2 className="text-lg font-medium mb-2">Additional Information</h2>
            <p>
              This warm winter coat is in excellent condition and will provide much-needed warmth for someone in need.
            </p>
          </div>
        </div>
        <div>
          <div className="mb-6">
            <h1 className="text-2xl font-bold">Beneficiary Details</h1>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h2 className="text-lg font-medium mb-2">Full Name</h2>
              <p>John Doe</p>
            </div>
            <div>
              <h2 className="text-lg font-medium mb-2">Email</h2>
              <p>john@example.com</p>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-4">
            <div>
              <h2 className="text-lg font-medium mb-2">Phone Number</h2>
              <p>+1 (123) 456-7890</p>
            </div>
            <div>
              <h2 className="text-lg font-medium mb-2">Address</h2>
              <p>
                123 Main St.
                <br />
                Anytown, CA 12345
              </p>
            </div>
          </div>
          <div className="mt-6">
            <h2 className="text-lg font-medium mb-2">Donation Status</h2>
            <div className="bg-green-100 text-green-800 px-4 py-2 rounded-md inline-block">Received</div>
          </div>
        </div>
      </div>
    </div>
  )
}
