/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DR65whra2qP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select } from "@/components/ui/select"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import Image from "next/image"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "./ui/tabs"
import IndividualForm from "./IndividualForm"
import OrganizationForm from "./OrganizationForm"
import { ArrowRightIcon } from "lucide-react"
import CustomButton from "./Button"

export function Register({
  title="Donor Registration",
  caption="Create an account to start donating",
  link="/app/donor"
}) {
  return (
    <div className="container mx-auto min-h-[calc(100vh-160px)]">
      <div className="grid grid-cols-1 lg:grid-cols-[65%_35%] h-full w-full">
        <div className="flex-1 flex items-center lg:pr-16">
          <div className="flex flex-col gap-y-12 w-full sm:px-6 lg:px-8">
            <div className="space-y-1">
              <h1 className="text-3xl font-bold">{title}</h1>
              <p className="text-muted-foreground">{caption}</p>
            </div>
            <Tabs defaultValue="individual"  className="space-y-4">
              <div className="space-y-2">
                <div className="flex items-center space-x-4">
                  <TabsList className="p-0">
                    <TabsTrigger value="individual">Individual</TabsTrigger>
                    <TabsTrigger value="organization">Organization</TabsTrigger>
                  </TabsList>
                </div>
              </div>
              <TabsContent value="individual">
                <IndividualForm />
              </TabsContent>
              <TabsContent value="organization">
                <OrganizationForm />
              </TabsContent>
            </Tabs>
            <CustomButton 
              icon={<ArrowRightIcon className="w-4 h-4" />}
              iconPosition="right"
              className="max-w-[200px] rounded-full py-6"
            >
              Register
            </CustomButton>
          </div>
        </div>
        <div className="flex-1 justify-center items-center hidden lg:flex pr-12">
          <div className="max-w-[500px] relative">
            <Image 
              src="/give-5.jpg" 
              alt="Register" 
              width={507} 
              height={760.5} 
              className="object-cover rounded-lg transform skew-x-[-4deg] blur-[3px]" 
            />
          </div>
        </div>
      </div>
    </div>
  )
}
