/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vdO0cwj027O
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Button } from "./ui/button"
import Link from "next/link"

export function SamaritanAccount() {
  return (
    <div className="w-full max-w-6xl mx-auto py-8 px-4 md:px-0 bg-secondary">
      <div className="flex flex-col gap-8">
        <div className="py-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-2xl font-bold mb-4">Profile</h2>
            <Link href="/app/samaritan/add-donation">
              <Button variant="outline">Add Donation</Button>
            </Link>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="text-sm font-medium text-muted-foreground">Full Name</label>
              <p className="text-base font-medium">John Doe</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">Email</label>
              <p className="text-base font-medium">john@example.com</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">Country</label>
              <p className="text-base font-medium">United States</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">Phone</label>
              <p className="text-base font-medium">+1 (555) 555-5555</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">Street Address</label>
              <p className="text-base font-medium">123 Main St</p>
            </div>
            <div>
              <label className="text-sm font-medium text-muted-foreground">City</label>
              <p className="text-base font-medium">Anytown</p>
            </div>
          </div>
        </div>
        <div className="bg-background rounded-lg shadow-md">
          <Tabs defaultValue="ongoing" className="">
            <TabsList className="border-b">
              <TabsTrigger value="ongoing">Ongoing Donations</TabsTrigger>
              <TabsTrigger value="past">Past Donations</TabsTrigger>
            </TabsList>
            <TabsContent value="ongoing">
              <div className="p-6">
                <h2 className="text-2xl font-bold mb-4">Ongoing Donations</h2>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Item Name</TableHead>
                      <TableHead>Item Category</TableHead>
                      <TableHead>Donation Status</TableHead>
                      <TableHead>Donation Date</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell><Link href="/app/samaritan/donation">Canned Food</Link></TableCell>
                      <TableCell>Food</TableCell>
                      <TableCell>
                        <Badge className="text-xs" variant="secondary">
                          New
                        </Badge>
                      </TableCell>
                      <TableCell>June 15, 2023</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Dog Toys</TableCell>
                      <TableCell>Pets</TableCell>
                      <TableCell>
                        <Badge className="text-xs" variant="secondary">
                          Assigned
                        </Badge>
                      </TableCell>
                      <TableCell>May 1, 2023</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </TabsContent>
            <TabsContent value="past">
              <div className="p-6">
                <h2 className="text-2xl font-bold mb-4">Past Donations</h2>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Item Name</TableHead>
                      <TableHead>Item Category</TableHead>
                      <TableHead>Donation Status</TableHead>
                      <TableHead>Donation Date</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell><Link href="/app/samaritan/donation">Clothing</Link></TableCell>
                      <TableCell>Apparel</TableCell>
                      <TableCell>
                        <Badge className="text-xs" variant="secondary">
                          Shipped
                        </Badge>
                      </TableCell>
                      <TableCell>March 10, 2023</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>School Supplies</TableCell>
                      <TableCell>Education</TableCell>
                      <TableCell>
                        <Badge className="text-xs" variant="secondary">
                          Received
                        </Badge>
                      </TableCell>
                      <TableCell>January 1, 2023</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </div>
  )
}
